name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-wiiu:
    name: 'Nintendo WiiU'
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install Dependents
      run: |
        dkp-pacman -S --noconfirm wut-sdl2
        git clone https://github.com/FFmpeg/FFmpeg.git --depth 1
        git clone https://github.com/rw-r-r-0644/ffmpeg-wiiu.git --depth 1
        cp ./ffmpeg-wiiu/configure-wiiu ./FFmpeg/configure-wiiu
        cd ./FFmpeg
        ./configure-wiiu
        make install -j
        cd ..

    - name: Build
      run: |
        cd ./cpymo-backends/sdl2
        make -j -f Makefile.WiiU
    
    - name: Upload
      uses: actions/upload-artifact@v2.3.0
      with:
        name: CPyMO for WiiU
        path: ./cpymo-backends/sdl2

